version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: peerloom-pearcircle-seeder_app_1
      APP_PORT: 8730

  app:
    image: ghcr.io/peerloomllc/pearcircle-seeder:0.1.4@sha256:a7b8f131e24606b6a15226a75a413137cb0205c9db7036a859e344da008dea26
    restart: on-failure
    stop_grace_period: 1m
    security_opt:
      - no-new-privileges:true
    environment:
      SEEDER_HOST: 0.0.0.0
      SEEDER_PORT: "8730"
      SEEDER_NO_AUTH: "1"
    volumes:
      - ${APP_DATA_DIR}/data:/data
