version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: peerloom-pearcircle-seeder_app_1
      APP_PORT: 8730

  app:
    image: ghcr.io/peerloomllc/pearcircle-seeder:0.1.1@sha256:efd3cc778ed17c7bfd2199f08bc3fd115e9f981fc302bb9ed9d3b421d2d63b57
    restart: on-failure
    stop_grace_period: 1m
    security_opt:
      - no-new-privileges:true
    environment:
      SEEDER_HOST: 0.0.0.0
      SEEDER_PORT: "8730"
      SEEDER_NO_AUTH: "1"
    volumes:
      - ${APP_DATA_DIR}/data:/data
