version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: peerloom-pearcircle-seeder_app_1
      APP_PORT: 8730

  app:
    image: ghcr.io/peerloomllc/pearcircle-seeder:0.1.3@sha256:a43c1cedcc89b01d8c7f341e204c267bdaa8aee813bfeec2060137d8d9a6d5d7
    restart: on-failure
    stop_grace_period: 1m
    security_opt:
      - no-new-privileges:true
    environment:
      SEEDER_HOST: 0.0.0.0
      SEEDER_PORT: "8730"
      SEEDER_NO_AUTH: "1"
    volumes:
      - ${APP_DATA_DIR}/data:/data
